### ISSUE TITLE
Cash shop item are given 2 time

### ISSUE THREAD

**Issue by openao42** [openao42o/OpenAo#3]
when you buy an item in the cash shop, this item go to your inventory and in the warehouse to so the item is duplicate

**Comment by St34lth4ng3l** [comment]
Would need to setup a testing environment to check this. But it kinda looks like a Database issue, that a procedure is executing wrong.

**Comment by openao42** [comment]
I will look at it when I will have time 2 team using my file report it to me already, my test environment is setup I have just to start it and do the test, it's will be done on the nexts weeks

**Comment by DeathRivals** [comment]
Simple 
Search this.
m_pFieldMapProject->GetShopInfoByBuildingNPC
