### ISSUE TITLE
Disconnect  close FieldServer

### ISSUE THREAD

**Issue by tiendey** [openao42o/OpenAo#4]
hi
 my server is Disconnect  its regular way
I checked the log is:
08-21 15:44:35|Socket Connect SocketIndex[219] PeerIP[  42.119.147.75] Port[16799]

please help me

**Comment by tiendey** [comment]
client disconcect (FieldWinsocket WS_CLOSE

**Comment by vinleprince** [comment]
i tested this soruce 3 month ago so i cant remember that much. if fieldserver disccount when client connecting. go check db produce with sql profiler. some mismatch param like mac adress have one error there.

**Comment by Guss42** [comment]
I will need more information to help you, use debbuger with pdb file to locate trouble ;)
