### ISSUE TITLE
Can't Compile ProjectServer/Gamerserver Solution

### ISSUE THREAD

**Issue by niyetsin** [openao42o/OpenAo#6]
Hello, I'm new here, and I'm looking for some advices on how to compile the project, I try to use VS2019, but I'm getting a bunch of errors, that I'm trying to fix, which some of those I'm not able to, due to the low knowledge of the code, that's why I'm asking here if someone can recommend, what program to use to compile this project without getting erros, If is possible. 
Here I'm going to attach the Issues that I have rightnow, trying to compile the GameServer Solution.

![image](https://user-images.githubusercontent.com/69861875/116796567-6aa10880-aaab-11eb-86a2-63024a1939bc.png)

I try to reduce the errors as much as I could, at first I got like 300+ Errors, but I'm thinking that my enviroment is not correctly setup or something like that.

![image](https://user-images.githubusercontent.com/69861875/116796631-fadf4d80-aaab-11eb-9ae5-25f5411f3320.png)

thank you

**Comment by BoyingtonDEV** [comment]
Hello,
Did you try with VS16 ?
The project compile successful.
